version: 2.1

executors:
  linux:
    docker:
      - image: electronuserland/builder:wine
  macos:
    macos:
      xcode: "11.4"

orbs:
  node: circleci/node@2.0.0

jobs:
  publish:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: false
      - run:
          name: "Hello!"
          command: "echo Hello, Word!!"

workflows:
  publish:
    when:
      or:
        - equal: [main, << pipeline.git.branch >> ]
        - equal: [development, << pipeline.git.branch >> ]
    jobs:
      - publish:
          matrix:
            parameters:
              os: [linux, macos]
              node-version: [16.13.0]
