version: 2.1

executors:
  linux:
    docker:
      - image: electronuserland/builder:wine
  macos:
    macos:
      xcode: 11.4

orbs:
  node: circleci/node@2.0.0

jobs:
  publish:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - run:
          name: "Hello!"
          command: "echo Hello, Word!!"

workflows:
  publish:
    filters:
      branches:
        only:
          - main
          - development
    jobs:
      - publish:
          test:
            matrix:
              parameters:
                os: [linux, macos],
                node-version: ["16.13.0"]

