version: 2.1

executors:
  linux:
    docker:
      - image: electronuserland/builder:wine
  macos:
    macos:
      xcode: "11.4"

orbs:
  node: circleci/node@2.0.0

jobs:
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: "NPM Install"
          command: "npm install"
      - run:
          name: "Build"
          command: "npm run build:main"
      - run:
          name: "Tests"
          command: "npm run test"
  publish:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: "NPM Install"
          command: "npm install"
      - run:
          name: "Package & Publish"
          command: "npx ts-node ./.erb/scripts/clean.js dist && npm run build && npx electron-builder build --publish onTag --win --linux"

workflows:
  publish:
    when:
      or:
        - equal: [main, << pipeline.git.branch >> ]
        - equal: [development, << pipeline.git.branch >> ]
    jobs:
      - publish:
          matrix:
            parameters:
              os: [linux]
              node-version: [16.13.0]
  test:
    when:
      or:
        - equal: [main, << pipeline.git.branch >> ]
        - equal: [development, << pipeline.git.branch >> ]
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]


env:

